server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: localhost:9092
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/appdatabase?authSource=admin
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_db
    username: postgres
    password: postgres
    hikari:
      schema: app_schema
      connection-ini-sql: CREATE SCHEMA IF NOT EXISTS app_schema

app:
  kafka:
    kafkaStatisticBookingTopic: "statistic-booking-topic"
    kafkaStatisticRegistrationTopic: "statistic-registration-topic"
    kafkaStatisticGroupId: "kafka-statistic-group-id"